name: varivate2
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - anyio=2.0.2=py38h578d9bd_3
  - argon2-cffi=20.1.0=py38h25fe258_2
  - async_generator=1.10=py_0
  - attrs=20.3.0=pyhd3deb0d_0
  - babel=2.9.0=pyhd3deb0d_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.1=py_0
  - bleach=3.2.1=pyh9f0ad1d_0
  - brotlipy=0.7.0=py38h8df0ef7_1001
  - ca-certificates=2020.12.5=ha878542_0
  - certifi=2020.12.5=py38h578d9bd_1
  - cffi=1.14.4=py38h261ae71_0
  - chardet=4.0.0=py38h578d9bd_0
  - cryptography=3.3.1=py38h3c74f83_0
  - cycler=0.10.0=py_2
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - descartes=1.1.0=py_4
  - entrypoints=0.3=pyhd8ed1ab_1003
  - freetype=2.10.4=h7ca028e_0
  - icu=67.1=he1b5a44_0
  - idna=2.10=pyh9f0ad1d_0
  - importlib-metadata=3.3.0=py38h578d9bd_2
  - importlib_metadata=3.3.0=hd8ed1ab_2
  - ipykernel=5.4.2=py38h81c977d_0
  - ipython=7.19.0=py38h81c977d_0
  - ipython_genutils=0.2.0=py_1
  - jedi=0.18.0=py38h578d9bd_1
  - jinja2=2.11.2=pyh9f0ad1d_0
  - json5=0.9.5=pyh9f0ad1d_0
  - jsonschema=3.2.0=py_2
  - jupyter_client=6.1.7=py_0
  - jupyter_core=4.7.0=py38h578d9bd_0
  - jupyter_server=1.1.4=py38h578d9bd_0
  - jupyterlab=3.0.1=pyhd8ed1ab_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jupyterlab_server=2.0.0=pyhd8ed1ab_0
  - kiwisolver=1.3.1=py38h82cb98a_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libblas=3.9.0=7_openblas
  - libcblas=3.9.0=7_openblas
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.5.0=hae1eefd_17
  - libgfortran4=7.5.0=hae1eefd_17
  - liblapack=3.9.0=7_openblas
  - libopenblas=0.3.12=pthreads_hb3c22a3_1
  - libpng=1.6.37=h21135ba_2
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - markupsafe=1.1.1=py38h8df0ef7_2
  - matplotlib-base=3.2.2=py38h5d868c9_1
  - mistune=0.8.4=py38h25fe258_1002
  - mizani=0.7.2=pyhd8ed1ab_0
  - nbclassic=0.2.5=pyhd8ed1ab_0
  - nbclient=0.5.1=py_0
  - nbconvert=6.0.7=py38h578d9bd_3
  - nbformat=5.0.8=py_0
  - ncurses=6.2=he6710b0_1
  - nest-asyncio=1.4.3=pyhd8ed1ab_0
  - notebook=6.1.6=py38h578d9bd_0
  - openssl=1.1.1i=h27cfd23_0
  - packaging=20.8=pyhd3deb0d_0
  - palettable=3.3.0=py_0
  - pandoc=2.11.3.2=h7f98852_0
  - pandocfilters=1.4.2=py_1
  - parso=0.8.1=pyhd8ed1ab_0
  - patsy=0.5.1=py_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pip=20.3.3=py38h06a4308_0
  - plotnine=0.7.1=py_0
  - prometheus_client=0.9.0=pyhd3deb0d_0
  - prompt-toolkit=3.0.9=pyha770c72_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pygments=2.7.3=pyhd8ed1ab_0
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyrsistent=0.17.3=py38h25fe258_1
  - pysocks=1.7.1=py38h924ce5b_2
  - python=3.8.5=h7579374_1
  - python-dateutil=2.8.1=py_0
  - python_abi=3.8=1_cp38
  - pytz=2020.5=pyhd8ed1ab_0
  - pyzmq=20.0.0=py38h1d1b12f_1
  - readline=8.0=h7b6447c_0
  - requests=2.25.1=pyhd3deb0d_0
  - send2trash=1.5.0=py_0
  - setuptools=51.0.0=py38h06a4308_2
  - six=1.15.0=pyh9f0ad1d_0
  - sniffio=1.2.0=py38h578d9bd_0
  - sqlite=3.33.0=h62c20be_0
  - statsmodels=0.12.1=py38h0b5ebd8_1
  - terminado=0.9.2=py38h578d9bd_0
  - testpath=0.4.4=py_0
  - tk=8.6.10=hbc83047_0
  - tornado=6.1=py38h25fe258_0
  - traitlets=5.0.5=py_0
  - urllib3=1.26.2=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zeromq=4.3.3=h58526e2_3
  - zipp=3.4.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - joblib==1.0.0
    - matplotlib==3.3.3
    - numpy==1.19.5
    - pandas==1.2.0
    - pillow==8.1.0
    - prince==0.7.0
    - scikit-learn==0.24.0
    - scipy==1.6.0
    - threadpoolctl==2.1.0
prefix: /home/z/anaconda3/envs/varivate2
